package handlers

import (
	"testing"

	"github.com/ralph/industrial-edge-middleware/internal/tagsheet"
)

func TestASheetPreviewSaysWhatEachRowWouldDo(t *testing.T) {
	existing := map[string]existingTag{
		"DB1.DBD0": {id: 1, sheetTag: tagsheet.Tag{Alias: "Temp", Address: "DB1.DBD0", DataType: "REAL", Unit: "°C", Decimals: 1}},
		"DB1.DBD4": {id: 2, sheetTag: tagsheet.Tag{Alias: "Press", Address: "DB1.DBD4", DataType: "REAL", Unit: "bar"}},
		"DB9.DBD0": {id: 3, udt: true, sheetTag: tagsheet.Tag{Alias: "Motor.Speed", Address: "DB9.DBD0", DataType: "REAL"}},
	}
	sheet := tagsheet.Parse([]byte(
		"Nome;Indirizzo;Tipo;Unità\n" +
			"Temp;DB1.DBD0;REAL;°C\n" + // same as stored (decimals not in the sheet)
			"Pressione;DB1.DBD4;REAL;bar\n" + // renamed
			"Nuovo;DB1.DBD8;INT;\n" + // new
			"Motor.Speed;DB9.DBD0;REAL;\n" + // generated by a UDT instance
			"Rotto;DB1.DBD12;WORD;\n")) // invalid type
	res := planSheet(sheet, existing)

	want := []string{"unchanged", "update", "create", "invalid", "invalid"}
	for i, r := range res.Rows {
		if r.Action != want[i] {
			t.Errorf("line %d (%s): %s, want %s — problems %v", r.Line, r.Alias, r.Action, want[i], r.Problems)
		}
	}
	if got := res.Rows[1].Changes; len(got) != 1 || got[0] != "alias" {
		t.Errorf("the rename reports changes %v, want [alias]", got)
	}
	if res.Rows[3].Problems[0].Code != "udt_managed" {
		t.Errorf("a UDT-generated tag is refused with %v", res.Rows[3].Problems)
	}
	if res.Created != 1 || res.Updated != 1 || res.Unchanged != 1 || res.Invalid != 2 {
		t.Errorf("counts: %+v", res)
	}
	// An empty unit cell on a new row is "not given": it must not show as a
	// change to "" on an existing one.
	if len(res.Rows[0].Changes) != 0 {
		t.Errorf("an identical row reports changes %v", res.Rows[0].Changes)
	}
}

func TestAMissingColumnLeavesAnExistingValueAlone(t *testing.T) {
	existing := map[string]existingTag{
		"40001": {id: 1, sheetTag: tagsheet.Tag{Alias: "P", Address: "40001", DataType: "INT", Scaling: true, RawMax: 27648, EuMax: 10}},
	}
	sheet := tagsheet.Parse([]byte("Name,Address,Type\nP,40001,INT\n"))
	res := planSheet(sheet, existing)
	if res.Rows[0].Action != "unchanged" {
		t.Errorf("a sheet without scaling columns would change %v", res.Rows[0].Changes)
	}
}
